version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortener-app
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017"
    depends_on:
      - mongodb

volumes:
  mongo-data: